### ISSUE TITLE
Add a section of team member names, roles along with the strengths in README.md

### ISSUE THREAD

**Issue by nishantarora23** [nishantarora23/Innovators-Soen6011summer2023#1]
`Description`
As part of the project documentation, we need to include a section in the README.md file that lists the team members' names, roles, and their respective strengths. This will provide visibility and acknowledgment of each team member's contributions and expertise.

`Acceptance Criteria`
The below information of team member name, role, strength and GitHub id must be available in the tabular format in the README.md file.

Team members and Roles:
**Gagandeep** 
github id: gaganpandher
role: Product Owner
**Karansinh Matroja** 
github id: metro161297
role: Business Analyst  
**Merlin Mary Abraham**
github id: merlinabraham95
role:  Architect
**Navdeep Kaur** 
github id: 4navdeep
role: QA
**Navjot Kamboj**
github id: navkamboj
role: Scrum Master        
**Nishant Arora**
github id: nishantarora23
role: Project Manager
_____________________________________________

`Additional Information`

**Story Points: 1**
**Priority:** Medium

**Comment by 4navdeep** [comment]
Added the team details to README.md file
