### ISSUE TITLE
UAT-003 Test Login for Employee/Student/Admin

### ISSUE THREAD

**Issue by merlinabraham95** [nishantarora23/Innovators-Soen6011summer2023#119]
**Description**

`Preconditions/Data`
1. Employer/Student should be registered through the sign up page.
2. Employer/Student should have username and password to login.

`Steps to Execute`
1. Enter either Username or Password on the Home page and click Login button
3. Enter both Username and Password > Click Login button

`Expected Result`
1. Username/Password is required message is displayed 
2. Employer/ Student / Admin are able to login successfully and can access their dashboard
______________________________________________________

`Additional Information`
**Priority: High**
**Severity: Highest**
**UserStory Link: #16**

**Comment by nishantarora23** [comment]
This UAT testcase is working as per the provided expectation. Therefore, closing the UAT.
