### ISSUE TITLE
UAT-004 Test Landing page for the website

### ISSUE THREAD

**Issue by merlinabraham95** [nishantarora23/Innovators-Soen6011summer2023#120]
**Description**

`Preconditions/Data`
1. Employer/Student/Admin should have internet connectivity.
2. Employer/Student/Admin should have access to the CareerConnect URL.

`Steps to Execute`
1. Verify information provided during signUp is visible on the Employer/Student dashboard 
2. Verify resume builder, skill assessment, job alerts, my jobs options are available in student dashboard
3. Verify Add Job offer/ My job offer options are present in Employer dashboard
4. Verify View all Employers/ Candidates options on Admin dashboard

`Expected Result`
1. Employer name, position, company name , emailID, Username, signup date and time is displayed on the employee dashboard.
2. Student name, college/university, DOB, username is displayed on the student dashboard
3.  Expected options are present 
4. Expected options are present 
5. Expected options are present
______________________________________________________

`Additional Information`
**Priority: High**
**Severity: Highest**
**UserStory Link: #17**

**Comment by nishantarora23** [comment]
Bug reported for this UAT, #149, #150 are working fine along with the associated functionality. Therefore closing the UAT.
