### ISSUE TITLE
Signup for Employer

### ISSUE THREAD

**Issue by merlinabraham95** [nishantarora23/Innovators-Soen6011summer2023#14]
`Description`
**As a** potential employer,
**I want to** sign up for an account on the platform,
**So that I can** access and utilize the features and services provided.

`Scenario`
Jane, a hiring manager, visits the CareerConnect website and signs up for an employer account by providing her name, email, password, and company details. After activation of her account she gains access to the platform's employer feature.

`Acceptance Criteria`
- There is a sign-up page with input fields for relevant information such as name, email,username, password, and company details.
- The sign-up form validates the input fields to ensure that required information is provided and follows any specified format or constraints.
- Upon successful submission of the sign-up form, an account is created for the employer with the provided information.
- If the employer's username is already registered, appropriate error messages are displayed, indicating that the username is already associated with an existing account.
- Upon succesfull login, it should redirect to employer's dashboard

________________________________
`Additional Information`

**Epic Link:** #7
**Story Points:** 3
**Priority:** High

________________________________
`Risk Management`

Risk : Multiple Users with same username
**Impact:** High
**Probability:**  Medium
**Counter Measures:** 
Username Validation: Implement a robust username validation system during the signup process that checks for the availability of a chosen username and ensures its uniqueness among existing users.

**Comment by gaganpandher** [comment]
- [x] Design Signup redirection from Landing Page
- [x] Create Signup for Employer
- [x] Create Form for details
- [x] User Input validation 
- [x] Testing the UI
