### ISSUE TITLE
Student DOB incorrect on Student Dashboard

### ISSUE THREAD

**Issue by merlinabraham95** [nishantarora23/Innovators-Soen6011summer2023#149]
`Description`
The DOB of the student displayed on the student dashboard is incorrect. It is always "August 24, 1995" for all the students.

`Steps to replicate the issue`
1. Create a student profile from the Sign Up page and give DOB different than August 24, 1995.
2. Login using username and password created in the previous step.
3. Student dashboard is showing DOB as "August 24, 1995".

`Screenshots`
![image](https://github.com/nishantarora23/Innovators-Soen6011summer2023/assets/85784587/729f30df-9344-4a2e-8ebd-a6b1c9c0992c)

`Expected Behavior`
The DOB must be same as entered by the Student during signup.

______________________________________________________

`Additional Information`

**Story Points: 1**
**Priority: High**
**Severity: Low**
**UAT Failure: #120 UAT-004**

**Comment by nishantarora23** [comment]
The fix provided is working fine. Therefore marking the UAT test as passed and closing the bug.

**Comment by merlinabraham95** [comment]
The fix provided is working fine. Therefore marking the UAT test as passed and closing the bug.
