### ISSUE TITLE
Signup for Student

### ISSUE THREAD

**Issue by merlinabraham95** [nishantarora23/Innovators-Soen6011summer2023#15]
`Description`
**As a** prospective student,
**I want to** sign up for an account on the platform,
**So that I can** explore educational opportunities and access student-specific features and resources.

`Scenario`
John, a high school student, signs up for a student account on the platform, providing his name, email, password, and educational background. After account creation, he gains access to educational resources and student-specific features, empowering him to explore academic opportunities.

`Acceptance Criteria`
- A sign-up page is available with input fields for necessary information, such as name, email, username, password, and educational background.
- The sign-up form validates the input fields to ensure required information is provided and follows any specified format or constraints.
- Upon successful submission of the sign-up form, an account is created for the student with the provided information.
- If the student's username is already registered, appropriate error messages are displayed, indicating that the username is associated with an existing account.

________________________________
`Additional Information`

**Epic Link:** #7 
**Story Points:** 3
**Priority:** High
________________________________
`Risk Management`

Risk : Multiple Users with same username
**Impact:** High
**Probability:**  Medium
**Counter Measures:** 
Username Validation: Implement a robust username validation system during the signup process that checks for the availability of a chosen username and ensures its uniqueness among existing users.

**Comment by gaganpandher** [comment]
- [x] Design Signup redirection from Landing Page
- [x] Create Signup for Student
- [x] Create Form for details
- [x] User Input validation 
- [x] Testing the UI
