### ISSUE TITLE
Add missing comments in the code base

### ISSUE THREAD

**Issue by navkamboj** [nishantarora23/Innovators-Soen6011summer2023#156]
`Description`
The code base lacks required comments at specific locations, resulting in reduced comprehensibility for other contributors. This issue hampers collaboration and the overall maintenance of the software.

`Steps to replicate the issue`
1.Clone the repository containing the code base.
2.Navigate to the relevant module or section of the code.
3.Analyze the code for missing comments where they are required for clarity and understanding.

`Expected Behavior`
Code comments are present at critical junctures in the code base to provide explanations, context, and guidance to other contributors.

______________________________________________________

`Additional Information`

**Story Points: 1**
**Priority: ** High
**Severity: ** Low

**Comment by gaganpandher** [comment]
added missing comments to the code base in #164
