### ISSUE TITLE
Landing page for the website

### ISSUE THREAD

**Issue by merlinabraham95** [nishantarora23/Innovators-Soen6011summer2023#17]
`Description`
**As a** visitor to the "CareerConnect" website,
**I want to** see an informative and visually appealing landing page,
**So that I can** quickly understand the platform's purpose and navigate to relevant sections.

`Scenario`
A job seeker, Sarah, visits the "CareerConnect" website and is captivated by the visually appealing landing page. She quickly grasps the platform's mission to connect job seekers with opportunities. Impressed by the user-friendly design, she eagerly signs up, excited about the potential career prospects offered by "CareerConnect."

`Acceptance Criteria`
- The landing page displays a clear and concise overview of the platform's key features and benefits.
- It includes visually appealing elements such as logo, images, graphics, and engaging content to capture the visitor's attention.
- It includes prominent calls to action (CTAs) that direct visitors to sign up, learn more, or access specific features.
- The landing page is optimized for different devices and screen sizes, ensuring a seamless user experience across desktop and mobile platforms.

________________________________
`Additional Information`

**Epic Link:** #7
**Story Points:** 1
**Priority:** High

**Comment by nishantarora23** [comment]
- [x] Design the Landing page
- [x] Routing App
- [x] Design approval

**Comment by nishantarora23** [comment]
![LandingPage](https://github.com/nishantarora23/Innovators-Soen6011summer2023/assets/42149632/73c3ade9-b362-4a19-82cf-774db2db2071)

**Comment by nishantarora23** [comment]
The design was approved and incorporated in the project.
