### ISSUE TITLE
Add Project Description section for CareerConnect in README.md

### ISSUE THREAD

**Issue by 4navdeep** [nishantarora23/Innovators-Soen6011summer2023#2]
`Description`
Add Project details in the README.md file.

`Acceptance Criteria`
1. Project Description added to the README.md file.
2. Project Description provides a concise summary of project's objective, features and constraints.
3. Project Description highlights the intended audience and users of the project.
4. Project Description provides the key deliverables.

_____________________________________________

`Additional Information`

**Story Points: 1**
**Priority:  Medium**

**Comment by navkamboj** [comment]
Updated Project description to README.md
