### ISSUE TITLE
Apache Tomcat Setup for Backend

### ISSUE THREAD

**Issue by nishantarora23** [nishantarora23/Innovators-Soen6011summer2023#20]
`Description`
This task involves setting up Apache Tomcat for the backend of the "CareerConnect" website. Apache Tomcat will be used to deploy Java Servlets and handle HTTP requests to support the website's server-side functionality.

`Acceptance Criteria`
- Identify the appropriate version of Apache Tomcat based on project requirements and compatibility with the backend code.
- Install and configure Apache Tomcat on the designated server or hosting environment.
- Configure the server.xml and web.xml files to define the necessary server settings and servlet mappings.
- Deploy the backend code, including the Java Servlets, to the Apache Tomcat server.
- Verify that the deployed Servlets are accessible and functional by performing comprehensive testing.
- Implement security measures, such as SSL/TLS configuration and secure communication protocols, to ensure data integrity and protection.
- Document the Apache Tomcat setup process, including configuration details and deployment steps, for future reference and maintenance purposes.
- Collaborate with the team to ensure proper integration between the frontend and backend components of the website.
_____________________________________________

`Additional Information`

**Story Points: 3**
**Priority:** Highest

**Comment by 4navdeep** [comment]
Tomcat setup completed
