### ISSUE TITLE
Add Core features in the README.md

### ISSUE THREAD

**Issue by nishantarora23** [nishantarora23/Innovators-Soen6011summer2023#22]
Description
As part of the project documentation, we need to include a section in the README.md file that lists the 4 main core features of Connect web application. This will provide high-level overview of the core features.

Acceptance Criteria
Create a tabular format which includes S.No., Core feature name, Issue link, Description, and Priority.
_____________________________________________

`Additional Information`

**Story Points: 1**
**Priority:** High
**Reference** #7, #8, #9, #10

**Comment by gaganpandher** [comment]
added core features in #26
