### ISSUE TITLE
Upload resume for a job offer

### ISSUE THREAD

**Issue by gaganpandher** [nishantarora23/Innovators-Soen6011summer2023#23]
`Description`
**As a** student 
**I want to**be able to upload my resume for a specific job offer on the Career connect.
**So that employers can** easily review my application and qualifications for the position.

`Scenario`
1. Emily logs into her student account on the career services platform.
2. She navigates to the job listing where she wants to apply.
3. Emily reviews the job requirements and details to ensure it aligns with her skills and interests.
4. On the job application page, Emily sees a section to select her resume.
5. She clicks on the resume selection field, which displays the available resumes on her profile.
6. Emily selects resume , ensuring that it is the most relevant and up-to-date version.
7. The platform confirms the selection of the resume and displays its name or identifier in the resume selection field.
8. Emily proceeds to complete the remaining sections of the job application, such as providing additional information or answering specific questions.
9. After filling out the necessary application details, Emily submits her application.
10. The platform confirms the successful submission of the job application and provides Emily with a confirmation message or notification.

`Acceptance Criteria`
1. The career services platform should provide a clear and accessible resume selection field within the job application page.
2. The platform should ensure that only the resume generated by the user is displayed.
3. The platform should validate the completion of all required sections in the job application before allowing the user to submit it.
4. Upon successful submission of the job application, the platform should provide the user with a confirmation message or notification.
5.The resume selected for the job application should be securely stored and only accessible by the employer for the specific job application.

________________________________
`Additional Information`

**Epic Link: #9**
**Story Points: 3**
**Priority: High**

________________________________
`Risk Management`

**Risk:** Allowing unrestricted file formats may lead to the upload of potentially dangerous file types, such as executable files (e.g., .exe, .bat), scripts, or other unsafe formats.

**Impact:** High
**Probability:** Medium

**Counter Measures:** 
- Limit accepted file types to safe document formats commonly used for resumes (e.g., PDF, DOC, DOCX).
- Use server-side validation to check the file's extension and reject uploads of unsupported file types.
- Apply content-type verification to ensure the file format matches the file extension.

**Comment by nishantarora23** [comment]
- [x] Frontend implementation for upload resume button (@merlinabraham95 ) SP: 1
- [x] Create API to store the uploaded resume  (@nishantarora23  ) SP: 1
- [x] Testing upload resume functionality (@gaganpandher ) SP: 1
