### ISSUE TITLE
Track job postings and applications by the admin

### ISSUE THREAD

**Issue by gaganpandher** [nishantarora23/Innovators-Soen6011summer2023#25]
`Description`
**As an**admin of the career Career connect
**I want to** be able to track job postings and applications.
**So that I can**ensure smooth operation and provide support to employers and students.

`Scenario`
1. The admin logs into the admin panel of the career services platform using their authorized credentials.
2. Upon accessing the admin panel, the admin is presented with a dashboard that provides an overview of job postings and applications.
3. The admin navigates to the "Job Postings" section, where a list of active job postings is displayed.
4. The admin reviews the job postings to ensure they comply with platform guidelines and requirements.
5. If any job posting violates the guidelines, the admin takes appropriate action, such as contacting the employer to rectify the issue or removing the posting if necessary.
6. The admin then moves to the "Applications" section to track the received applications for various job postings.
7. The applications are displayed in a list format, showing relevant details such as the candidate's name, application status, and the job they applied for.
8. The admin can filter and sort applications based on criteria such as job title, candidate name, or application status.
9. For each application, the admin can view the candidate's submitted resume and other supporting documents, if available.
10. The admin can update the application status (e.g., shortlisted, rejected, interview scheduled) based on the employer's decisions or assessments.
11. In case of any issues or discrepancies in the application process, the admin can contact the candidate or the employer for further clarification or resolution.
12. The admin can generate reports or export data related to job postings and applications for analysis or record-keeping purposes.
13. Throughout the tracking process, the admin ensures the confidentiality and security of the candidate's personal information and application data.
14. The admin performs regular monitoring and maintenance tasks to keep the job postings and applications section up-to-date and error-free.

`Acceptance Criteria`

1. The admin panel should provide a user-friendly and intuitive interface for the admin to track job postings and applications effectively.
2. The job postings section should display a list of active postings with essential details, such as job title, employer name, and posting status.
3. The admin should be able to review and manage job postings, including editing, removing, or contacting the employer if needed.
4. The applications section should present a comprehensive list of received applications, showing relevant information like candidate names, application status, and the associated job postings.
5. The admin should be able to filter and sort applications based on different criteria, enabling efficient tracking and management.
6. The admin should be able to update application status, allowing them to reflect the employer's decisions or actions accurately.
7. The platform should ensure the security and privacy of candidate data, adhering to applicable data protection regulations.
8. The admin should be able to generate reports or export data related to job postings and applications for analysis or record-keeping purposes.
9. The admin panel should be regularly maintained and monitored to ensure its functionality, accuracy, and security.
________________________________
`Additional Information`

**Epic Link: ** #8 
**Story Points: **3
**Priority: **High

`Risk Management`
Risk: Application Mismanagement

Impact Level: Medium
Probability: Medium

Counter measures:
1. Implement a well-defined workflow for job applications, including status updates and communication with applicants.
2. Provide a dashboard overview for the admin to easily monitor the progress of each application.

**Comment by metro161297** [comment]
- [x]  Frontend Implementation for tracking job postings (@metro161297 ) SP: 1
- [x]  Create API to view job postings and application details (@gaganpandher ) SP: 1
- [x]  Testing (@nishantarora23  ) SP: 1
