### ISSUE TITLE
Ability to view all user profiles from Admin dashboard

### ISSUE THREAD

**Issue by navkamboj** [nishantarora23/Innovators-Soen6011summer2023#29]
`Description`
**As an** administrator
**I want to** view all the user profiles from my dashboard
**So that I can** easily manage all the users

`Scenario`
Jason, an administrator of CareerConnect application, desires the ability to view all the employers and job-seekers who have signed up for CareerConnect services and are actively leveraging the functionalities. This enables him to easily monitor and manage all the  users. 

`Acceptance Criteria`
1. Administrator must be able to view list of all the students or job-seekers who have signed up by clicking on 'View Student profiles' 
2. Administrator must be able to view list of all the employers who have signed up by clicking on 'View Employer profiles'
3. Administrator must be able to select a particular job-seeker to view his profile and see additional details like his email Id, educational background, work experience, skills , etc.
4. Administrator must be able to select a particular employer to view his profile and see additional details like his email Id and other company details. 

________________________________
`Additional Information`

**Epic Link:** #8 
**Story Points:** 3
**Priority:** High

`Risk Management`
**Risk:** Data Privacy Concerns

**Impact Level:** High
**Probability:** Medium

**Counter measures:**
1. Anonymize or pseudonymize sensitive user information where possible.
2. Apply the principle of least privilege to limit access to user profiles to authorized administrators only.

**Comment by metro161297** [comment]
- [x] Frontend Implementation for viewing Student and Employer Profiles (@metro161297 ) SP: 1
- [x] Create API to get data for user profiles (@gaganpandher ) SP: 1
- [x] Testing (@merlinabraham95 ) SP: 1
