### ISSUE TITLE
Ability to view all user postings from Admin dashboard

### ISSUE THREAD

**Issue by navkamboj** [nishantarora23/Innovators-Soen6011summer2023#30]
`Description`
**As an** administrator
**I want to** view all the user postings from my dashboard
**So that I can** easily manage all the postings

`Scenario`
Jason, an administrator of CareerConnect application, desires the ability to view all the job-postings done by an employer and all the jobs a candidate applied to. This enables him to easily manage all the user postings. 

`Acceptance Criteria`
1. Administrator must be able to view list of all the students or job-seekers who have signed up by clicking on 'View Student profiles'
2. Administrator must be able to view list of all the employers who have signed up by clicking on 'View Employer profiles'
3.  Administrator must be able to select a particular employer from the list of all employers and select 'Display job postings' option to see the list of all the jobs he has posted. 
4. Administrator must be able to select a particular job-seeker from the list of all candidates and select 'Display applied jobs' option to view the list of all the jobs he/she has applied to.

________________________________
`Additional Information`

**Epic Link:** #8
**Story Points:**3
**Priority:** High

`Risk Management`
**Risk:** Data Privacy Concerns

**Impact Level:** High
**Probability:** Medium

**Counter measures:**
1. Anonymize or pseudonymize sensitive user information where possible.
2. Apply the principle of least privilege to limit access to user profiles to authorized administrators only.

**Comment by metro161297** [comment]
- [x]  Frontend Implementation for viewing user postings (@metro161297 ) SP: 1
- [x]  Create API to get data for user postings (@gaganpandher ) SP: 1
- [x]  Testing (@merlinabraham95 ) SP: 1
