### ISSUE TITLE
Ability to Add/Remove user-profiles from Admin dashboard

### ISSUE THREAD

**Issue by navkamboj** [nishantarora23/Innovators-Soen6011summer2023#31]
`Description`
**As an** administrator
**I want to** have the ability to add or remove user profiles from my dashboard
**So that I can** efficiently manage user accounts

`Scenario`
Jason, an administrator of CareerConnect application, desires the ability to remove employers' and job-seekers' account if they are no longer actively used.  He also wants to have the feature to add the removed employers or candidate profiles , if needed. 

`Acceptance Criteria`
1. Administrator must be able to view list of all the students or job-seekers who have signed up by clicking on 'View Student profiles'
2. Administrator must be able to view list of all the employers who have signed up by clicking on 'View Employer profiles'
3. Administrator must be able to select a particular employer from the list and remove that employer.
4. Administrator must be able to select a particular job-seeker from the list and remove that candidate. 
5. Deleted employer and candidate profiles must no longer be available in the database. 
6.  Employers and candidates who are removed from the CareerConnect platform must not be able to login into their accounts. 
7.  Administrator must have the ability to see the list of all the removed employers' and candidate accounts.
8.  Administrator must have the ability to 'Add' the removed profiles back .
9.  Added profiles must reflect back in the database and respective users should be able to access their accounts. 

________________________________
`Additional Information`

**Epic Link: ** #8 
**Story Points: **3
**Priority: ** High

`Risk Management`
Risk: Accidental User Profile Removal

Impact Level: High
Probability: Medium

Counter measures:
1. Implement a confirmation prompt or two-step verification when removing user-profiles to prevent accidental deletions.
2. Maintain a backup of user-profile data to facilitate recovery in case of unintentional removal.
3.

**Comment by metro161297** [comment]
- [x]  Frontend Implementation to Add/Remove Student / Employer profiles (@metro161297 ) SP: 1
- [x]  Create API to to Add/Remove user-profiles (@gaganpandher ) SP: 1
- [x]  Testing (@nishantarora23 ) SP: 1
