### ISSUE TITLE
Ability to Add/Remove user postings from Admin dashboard

### ISSUE THREAD

**Issue by navkamboj** [nishantarora23/Innovators-Soen6011summer2023#34]
`Description`
**As an** administrator
**I want to** have the ability to add or remove user postings from my dashboard
**So that I can** efficiently manage user postings

`Scenario`
Jason, an administrator of CareerConnect application, desires the ability to remove employers' job postings if the recruiter is no longer hiring for that job. He also wants to have the feature to add the removed job postings again , if needed.

`Acceptance Criteria`
1. Administrator must be able to select a particular employer from the list of all employers and select 'Display job postings' option to see the list of all the jobs he has posted.
2.  Administrator must have the option to delete a particular job posting.
3.  Deleted job posting must not be reflected in employer's account.
4.  Job seeker should not be able to view the deleted job-posting.
5.  Administrator should be able to see list of all the deleted job-postings.
6.  Administrator should have the option to add the removed job-postings, if required. 
7.  Added job-posting must reflect back under employers' job-postings and job-seeker must be able to view and apply for the same job. 

________________________________
`Additional Information`

**Epic Link: ** #8 
**Story Points: **3
**Priority: ** High

`Risk Management`
Risk: Accidental Post Removal

Impact Level: High
Probability: Medium

Counter measures:
1. Implement a confirmation prompt or two-step verification when removing user postings to prevent accidental deletions.
2. Provide an "Undo" or "Restore" option for a limited time after post removal.

**Comment by metro161297** [comment]
- [x]  Frontend Implementation to Add/Remove user Postings (@metro161297 ) SP: 1
- [x]  Create API to to Add/Remove user postings (@gaganpandher ) SP: 1
- [x]  Testing (@merlinabraham95 ) SP: 1
