### ISSUE TITLE
Track a job application by the candidate

### ISSUE THREAD

**Issue by 4navdeep** [nishantarora23/Innovators-Soen6011summer2023#36]
`Description`
**As a** Student
**I want to** track all job applications that I applied for,
**So that I can** be informed about the status of applications.

`Scenario`

1. Student (S) logs into their account on the Career Connect platform.
2. S navigates to the "Applied Jobs" section on their dashboard.
3. S can view a list of all the job offers that they applied.
4. The list displays the job details, including the job title, company name, location, candidate status and any other relevant information.

`Acceptance Criteria`
· Upon successful login, the student is directed to their dashboard.
· The dashboard has a dedicated section for applied jobs.
· The applied job section have all the jobs that candidate applied for.
· The page displays all the required information like, job title, company name, date applied, current status and any other relevant information.

________________________________

`Additional Information`

**Epic Link: ** #9 
**Story Points: **3
**Priority: ** High

________________________________
`Risk Management`

**Risk:** Candidates' personal information and application status may be accessible to unauthorized users or attackers if the system lacks proper security measures.

**Impact:** High
**Probability:** Medium

**Countermeasures:**
1. Implement robust user authentication mechanisms to ensure that only the applicant can access their application details.
2. Utilize strict access controls and role-based permissions to limit access to candidate data to authorized personnel only.
3. Regularly audit and monitor access logs for any suspicious activities or unauthorized access attempts.

**Comment by nishantarora23** [comment]
- [x] Frontend implementation for Track job (@merlinabraham95 ) SP: 1
- [x] Backend implementation to get job information from DB (@nishantarora23  ) SP: 1
- [x] Testing user flow for Track job (@gaganpandher ) SP: 1
