### ISSUE TITLE
Dashboard template for Employer/Student/Admin

### ISSUE THREAD

**Issue by metro161297** [nishantarora23/Innovators-Soen6011summer2023#37]
`Description`
**As an** Employer, Student, or Admin,
**I want to** access a user-friendly and informative dashboard template that provides a centralized view of relevant information and features based on my role. 
**So that I can** be able to view key metrics, notifications, and quick access to commonly used functionalities on dashboard.

`Scenario`

Employer:

- Upon logging in, the employer is directed to the dashboard.
- The employer sees an overview of their company's recent job postings, number of applicants, and any pending or completed hiring processes.
- The dashboard displays relevant metrics, such as the number of active job listings, open positions, and recent applicant activity.
- The employer can quickly navigate to manage job postings, review applicant profiles, and access other employer-specific features directly from the dashboard.

Student:

- After logging in, the student is presented with the dashboard.
- The dashboard provides an overview of the student's application status, including any pending or scheduled interviews and updates new listings.
- Important metrics, such as the number of applications submitted, interview invitations, and saved job searches, are displayed on the dashboard.
- The student can easily navigate to update their profile, search for job opportunities from the dashboard.

Admin:

- Upon logging in, the admin is directed to the dashboard.
- The dashboard provides a summary of system-wide statistics, such as the total number of registered employers, students, and active job listings.
- The admin can view new user registrations directly from the dashboard.
- Key administrative functions, including user management, content moderation, and system configuration, are easily accessible from the dashboard.
- The admin can generate reports, analyze data, and perform system-wide tasks from the dashboard.

`Acceptance Criteria`

- The dashboard template should be responsive, ensuring an optimal viewing experience on different devices and screen sizes.
- Role-specific information and functionalities should be displayed based on the user's role (Employer, Student, or Admin).
- The dashboard should present key metrics, such as job postings, applicants, application status, and system-wide statistics, in a easy-to-understand manner.
- Quick access links or buttons should be provided to navigate to important features or tasks related to the user's role.
- The dashboard template should be customizable, allowing future enhancements or modifications to cater to specific user preferences or business requirements.

________________________________
`Additional Information`

**Epic Link: #8 **
**Story Points: 1**
**Priority: High**

________________________________
`Risk Management`

Role-based Information Display Issues
**Impact:** Low
**Probability:** Medium
**Countermeasures:**
1. Implement robust role-based access control (RBAC) mechanisms to ensure users only see information and features relevant to their roles.
2. Conduct extensive testing with different user roles to verify that the dashboard displays the correct data and functionalities.
3. Regularly review and update RBAC settings to accommodate any changes in user roles or permissions.

Unauthorized Access to Administrative Functions
**Impact:** High
**Probability:** Medium
**Countermeasures:**
1. Limit administrative access to authorized personnel only.
2. Implement RBAC for administrative tasks to ensure that only designated admins can perform certain actions.
3. Use strong password policies and multi-factor authentication for admin accounts.

**Comment by merlinabraham95** [comment]
Dashboard template for all the users have been implemented
