### ISSUE TITLE
Add Job Offers from the Employer Dashboard

### ISSUE THREAD

**Issue by metro161297** [nishantarora23/Innovators-Soen6011summer2023#38]
`Description`
**As an** Employer,
**I want to** add new job offers directly from my dashboard. 
**So that I can** create and publish job listings in a convenient and streamlined way, ensuring they reach potential candidates effectively.

`Scenario`
Employer:

- Upon logging into the employer dashboard, the employer navigates to the "Job Offers" section.
- The employer selects the option to "Add New Job Offer" from the dashboard.
- A form is presented where the employer can enter relevant details about the job offer, including job title, description, required qualifications, responsibilities, and any other pertinent information.
- The employer can specify additional details such as job location, salary range, contract type, and application deadline.
- The form includes validation to ensure required fields are filled out correctly and any entered data meets the specified criteria.
- Once all necessary information is provided, the employer submits the job offer for review and publication.
- The employer receives a confirmation message indicating that the job offer has been successfully submitted for review

`Acceptance Criteria`

- The employer should be able to access the "Add New Job Offer" feature directly from the dashboard.
- The job offer form should include fields for relevant details such as job title, description, qualifications, responsibilities, location, salary, contract type, and application deadline.
- The form should include validation to ensure that required fields are filled out correctly and that any entered data meets the specified criteria (e.g., data type, character limits).
- Upon submitting the job offer, the system should provide a confirmation message to the employer, indicating that the job offer has been successfully submitted for review.
- The submitted job offer should be stored in a database or appropriate data storage, ready for further processing and publication.
- Any error or validation messages should be displayed clearly to the employer, indicating any required corrections or missing information in the job offer form.
- The employer should have the option to edit or delete a job offer if needed, providing appropriate permissions and access control.
- The job offer submission should trigger a review process by authorized personnel before it is published on the platform.
- The job offer submission and review process should adhere to any specific business rules, regulations, or policies applicable to the organization or industry.

________________________________
`Additional Information`

**Epic Link: #8**
**Story Points: 3**
**Priority: High**

________________________________
`Risk Management`

Data Breach or Security Vulnerabilities
**Impact:** High
**Probability:** Medium
**Counter Measures:** 
1. Implement robust data encryption for sensitive information (e.g., salary details).
2. Conduct regular security audits and vulnerability assessments.
3. Educate employees on data security best practices.
4. Monitor access controls and permissions to prevent unauthorized access.

Risk: Unauthorized Job Offer Publication
**Impact:** High
**Probability:** Low
**Countermeasures:**
1. Implement strict approval processes before publishing job offers.
2. Limit publication access to authorized personnel only.
3. Monitor publishing activities and log all actions related to job offer publication.

**Comment by 4navdeep** [comment]
Add job offer feature added
