### ISSUE TITLE
Select candidate for interview from Employer dashboard

### ISSUE THREAD

**Issue by metro161297** [nishantarora23/Innovators-Soen6011summer2023#39]
`Description`
**As an** Employer, 
**I want to** review job applications and select candidates for interviews directly from my dashboard. 
**So that I can** efficiently manage and schedule interviews with potential candidates.

`Scenario`

- Upon logging into the employer dashboard, the employer navigates to the "Job Applications" or "Candidates" section.
- The employer views a list of job applications received for a specific job offer or a consolidated list of all applications across multiple job offers.
- The dashboard presents relevant details of each candidate, such as their name, qualifications, and application status.
- The employer reviews the candidate profiles and application materials, such as resumes and cover letters, to assess their suitability for the position.
- From the candidate list, the employer selects one or multiple candidates to proceed to the interview stage.
- The employer clicks on a "Select for Interview" button or similar option to mark the chosen candidates.
- The system records the selection and may trigger notifications or alerts to the selected candidates.
- The employer can view the updated list of selected candidates for interview and proceed with scheduling interviews as necessary.

`Acceptance Criteria`

- The employer should be able to access the candidate selection feature from the dashboard, either in the "Job Applications" or "Candidates" section.
- The dashboard should display relevant candidate details, including their name, qualifications, and application status, for easy review and assessment.
- The employer should be able to review candidate profiles, resumes, and other application materials directly from the dashboard.
- The employer should have the option to select one or multiple candidates for the interview stage.
- The system should record the selection and update the candidate status accordingly.
- The employer should be able to view the updated list of selected candidates for interview from the dashboard.
- The system may trigger notifications or alerts to the selected candidates, informing them of their selection and providing further instructions if necessary.
- The employer should have the ability to schedule interviews with the selected candidates, either through the dashboard or via integrated scheduling tools.
- The candidate selection and interview scheduling process should adhere to any specific business rules, regulations, or policies applicable to the organization or industry.

________________________________
`Additional Information`

**Epic Link: #8 **
**Total Story Points: ** 3
FE : 1 
BE: 1 
QA: 1
**Priority: ** High

________________________________
`Risk Management`

Notification Errors:  The system may have issues with sending notifications or alerts to the selected candidates, leading to misunderstandings or missed interview opportunities.
**Impact:** High
**Probability:** Low
**Counter Measures:** 
Notification Verification: Employ a notification verification mechanism to ensure that selected candidates receive interview invitations accurately.

**Comment by 4navdeep** [comment]
- [x] View Resume : 1 SP
- [x] Select Candidate for interview : 1 SP
- [x] Notify Candidate : 1 SP
