### ISSUE TITLE
Apply for Job offers from the Student dashboard

### ISSUE THREAD

**Issue by metro161297** [nishantarora23/Innovators-Soen6011summer2023#40]
`Description`
**As a** Student
**I want to** browse and apply for job offers directly from my dashboard
**So that I can** easily search for relevant job opportunities, review job details, and submit applications efficiently.

`Scenario`

- Upon logging into the student dashboard, the student navigates to the "Job Offers" or "Job Search" section.
- The dashboard displays a list of available job offers, either personalized recommendations or a comprehensive listing.
- The student can filter and search for job offers based on criteria such as job title, location, industry, or keywords.
- The student selects a job offer from the list to view detailed information about the position.
- The job offer page presents relevant details, including job description, required qualifications, responsibilities, and application instructions.
- If interested and eligible, the student clicks on an "Apply" button or similar option to submit their application.
- The student is presented with an application form or process where they can enter additional information, attach their resume, and provide any requested documents.
- Once all necessary information is provided, the student submits the application.
- The system confirms the successful submission of the application and may provide a confirmation message or email to the student.

`Acceptance Criteria`

- The student should be able to access the job application feature from the student dashboard, either in the "Job Offers" or "Job Search" section.
- The dashboard should display a list of available job offers, including relevant details such as job title, location, and brief descriptions.
- The student should be able to search and filter job offers based on various criteria, such as job title, location, industry, or keywords.
- Clicking on a job offer should direct the student to a detailed job offer page with comprehensive information about the position.
- The job offer page should include the job description, required qualifications, responsibilities, and any specific application instructions.
- The student should be able to click on an "Apply" button or similar option to initiate the application process for the selected job offer.
- The application form or process should allow the student to enter additional information, attach their resume, and provide any requested documents.
- The system should validate the application form to ensure required fields are filled out correctly and any entered data meets the specified criteria (e.g., data type, character limits).
- Upon submitting the application, the system should provide a confirmation message or email to the student, confirming the successful submission.
- The submitted application should be stored in a database or appropriate data storage, ready for further processing and review by employers.
- The application process should adhere to any specific business rules, regulations, or policies applicable to the organization or industry.

________________________________
`Additional Information`

**Epic Link: #8 **
**Story Points: 3**
**Priority: High**

________________________________
`Risk Management`

Role-based Information Display Issues
**Impact:** Low
**Probability:** Medium
**Countermeasures:**
1. Implement robust role-based access control (RBAC) mechanisms to ensure users only see information and features relevant to their roles.
2. Conduct extensive testing with different user roles to verify that the dashboard displays the correct data and functionalities.
3. Regularly review and update RBAC settings to accommodate any changes in user roles or permissions.

Unauthorized Access to Administrative Functions
**Impact:** High
**Probability:** Medium
**Countermeasures:**
1. Limit administrative access to authorized personnel only.
2. Implement RBAC for administrative tasks to ensure that only designated admins can perform certain actions.
3. Use strong password policies and multi-factor authentication for admin accounts.

**Comment by nishantarora23** [comment]
- [x] Frontend implementation for Apply Job offer (@merlinabraham95 ) SP: 1
- [x] Backend implementation for Apply Job offer (@nishantarora23  ) SP: 1
- [x] Testing user flow for Apply Job offer (@gaganpandher ) SP: 1
