### ISSUE TITLE
Merging Sprint-1 Branch to Master

### ISSUE THREAD

**Issue by merlinabraham95** [nishantarora23/Innovators-Soen6011summer2023#42]
`Description`
The task involves merging the changes and updates made in the Sprint-1 branch into the master branch of the project. The purpose is to integrate the completed work from the Sprint-1 development cycle into the main codebase, ensuring that all the changes are properly incorporated and conflicts are resolved.

`Acceptance Criteria`
1. Review Changes:
   - Conduct a comprehensive review of all the changes and updates implemented in the Sprint-1 branch.
   - Understand the scope of the changes and their impact on the project.

2. Update the Sprint-1 Branch:
   - Ensure that the Sprint-1 branch is up-to-date with the latest changes from the master branch.
   - Pull the latest changes from the master branch and resolve any conflicts, if present.

3. Resolve Conflicts:
   - If conflicts occur during the merge process, carefully analyze and resolve them.
   - Collaborate with the team members, if necessary, to ensure a smooth resolution.

4. Test and Validate:
   - After merging, thoroughly test the merged code to ensure that it functions as expected.
   - Validate that the functionality implemented in the Sprint-1 branch is still intact and functioning correctly in the merged codebase.

5. Merge to Master:
   - Once all conflicts are resolved, the code has been thoroughly tested, and the necessary reviews and updates are completed, merge the Sprint-1 branch into the master branch.
   - Ensure that the merge process is executed correctly to avoid introducing any new issues or conflicts.
_____________________________________________

`Additional Information`

**Story Points: 0**
**Priority:** High

**Comment by nishantarora23** [comment]
Sprint-1 code changes have been merged in the master branch.
